### ISSUE TITLE
Add nextPage and prevPage methods to the controller

### ISSUE THREAD

**Issue by carman247** [alhappler/alh_pdf_view#18]
Just a small enhancement I thought might be nice. 

Would be great if you could choose the `Duration` and `Curve` for the animation.

**Comment by andreBalh** [comment]
Thank you for your feature request, I will look up to that later @carman247

**Comment by karvulf** [comment]
I have some updates for you @carman247 

I implemented the method `goToNextPage` and `goToPreviousPage`.
You can also use `withAnimation` for iOS.
I didn't add the possibility to change the duration or animation curve, because this would only be possible in iOS. 
To ensure that iOS and Android are having the same behavior, there is only the default value of 400 ms for the animation that can't be changed.

The upcoming release will be `1.0.0` that also required a min version of iOS 11 and is updated to flutter 3.3
